version: 0.2

env:
  variables:
    HUGO_VERSION: "0.56.3"
    HUGO_SHA256: "4c7d3dd394e0ea34e353418b81ab8123f07006a529b432436c361cb9d04987ed"

phases:
  install:
    commands:
    - echo "building"
    - curl -Ls https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
    - echo "${HUGO_SHA256}" /tmp/hugo.tar.gz" | sha256sum -c -
    - tar xf /tmp/hugo.tar.gz -C /tmp
    - mv /tmp/hugo /usr/bin/hugo
    - rm -rf /tmp/hugo*
  build:
    commands:
    - hugo
artifacts:
  files:
  - '**/*'
  base-directory: 'public'
