baseURL = "https://samsanders.dev/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Sam Sanders"
theme = "hallo"
googleAnalytics = "UA-143899138-1"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true

[Author]
  name = "Sam Sanders"

[params]
  greeting = "Hello!"
  description = "Sam Sanders is software developer and consultant based in Boulder, CO, USA."
  author = "Sam Sanders"
  email = "hello@samsanders.dev"
 
  [[params.links]]
    icon = "linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/samuelesanders/"

  [[params.links]]
    icon = "github"
    title = "GitHub"
    url = "https://github.com/p-ssanders"

  [[params.links]]
    iconset = "fas"
    icon = "envelope"
    title = "Email"
    url = "mailto:hello@samsanders.dev"

[params.colors]
  background = "#FAFAFA"
  foreground = "#212121"
  hover = "#d81b60"
