baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Sam Sanders"
theme = "hallo"
googleAnalytics = ""
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
  name = "Sam Sanders"

[params]
  greeting = "Hello!"
  description = "Sam Sanders is software developer and website consultant based in Boulder, CO, USA."
  author = "Sam Sanders"
  email = "hello@samsanders.dev"
 
  [[params.links]]
    iconset = "fas"
    icon = "envelope"
    title = "Email"
    url = "mailto:hello@samsanders.dev"

  [[params.links]]
    icon = "linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/samuelesanders/"

[params.colors]
  background = "#FAFAFA"
  foreground = "#212121"
  hover = "#d81b60"
